apiVersion: v1
kind: Service
metadata:
  name: springboot-podman-service
spec:
  selector:
    app: springboot-podman-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
